services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: horadoqa
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: horadoqa-postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: